name: test_task_flutter
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  get_it: ^8.0.3
  freezed: ^3.0.5
  equatable: ^2.0.7
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  logger: ^2.5.0
  json_annotation: ^4.9.0
  injectable: ^2.5.0
  auto_route: ^10.0.1
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  freezed_annotation: ^3.0.0
  retrofit_generator: ^9.1.9
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  injectable_generator: ^2.7.0
  auto_route_generator: ^10.0.1

flutter:
  uses-material-design: true